version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    container_name: "IRNet"
    command: sh -c "export PORT=3355 && npm start"
    tty: true
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    expose: 
      - 9090
    ports:
      - '9090:3355'
    networks:
      - default
      - kbc-net

networks:
  kbc-net:
    external: true
